### PR TITLE
Fix javadoc typos

### PR DESCRIPTION
**Pull request by Malax**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Malax Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=projectriff/java-function-invoker&pullRequestId=247)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=projectriff/java-function-invoker&pullRequestId=247) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by Malax** [comment]
@pivotal-issuemaster This is an Obvious Fix

**Comment by pivotal-issuemaster** [comment]
@Malax This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by scothis** [comment]
thanks @Malax

**Pull request merged**
