### PR TITLE
Remove windowing from wordcount sample

### PR DESCRIPTION
**Pull request by trisberg**
- update README instructions for wordcount

Also remove main class from uppercase sample, now detected by SCFn

### CODE REVIEW

**Comment by ericbottard** [comment]
Why not check in the yaml file?

**Comment by trisberg** [comment]
We still need to generate the Dockerfile and topics.yaml so made more sense to me to modify the function.yaml

**Comment by trisberg** [comment]
Rebased and modified READMEs

**Review by jldec — APPROVED** [review]
validated that this works as described.
LGTM

**Pull request merged**
