### PR TITLE
Support functions using Spring Boot 2.0

### PR DESCRIPTION
**Pull request by dsyer**
With a bit of reflection to call the right method we can start Spring Boot
1.5 and Spring Boot 2.0 functions from the same invoker app.

Fixes gh-49

(Applied on top of gh-47)

### CODE REVIEW

**Comment by trisberg** [comment]
Not having much success switching to Boot 2.0 for my demo app - https://gist.github.com/trisberg/b18490a7c0a5fd7a8a91277b4cb01659

Do I need to switch some dependencies?

I get:

```
Caused by: java.lang.IllegalStateException: Cannot launch
	at io.projectriff.invoker.ApplicationRunner.getError(ApplicationRunner.java:167)
	at io.projectriff.invoker.ApplicationRunner.run(ApplicationRunner.java:74)
	at io.projectriff.invoker.FunctionConfiguration$BeanCreator.run(FunctionConfiguration.java:246)
	at io.projectriff.invoker.FunctionConfiguration.init(FunctionConfiguration.java:128)
	... 25 more
Caused by: java.lang.NoSuchMethodError: org.springframework.boot.builder.SpringApplicationBuilder.<init>([Ljava/lang/Object;)V
	at io.projectriff.invoker.ContextRunner$1.run(ContextRunner.java:57)
	... 1 more
```

Also, running as a standalone web app I get `["HELLO"]` back for app with Boot 2.0 while the same app with 1.5.10 returns `HELLO`.

**Comment by trisberg** [comment]
Never mind, forgot to change the Dockerfile to use 0.0.6-snapshot, it works now with function built with Boot 2.0. The running app use v1.5.10.RELEASE though. Maybe it's time to go full 2.0 for the invoker part as well.

**Comment by dsyer** [comment]
1.5.10 is still faster. If we care about that we should stick. Can we just merge this though (seems like an orthogonal discussion)?

**Comment by trisberg** [comment]
Yes, I agree, will merge ...

**Comment by trisberg** [comment]
Rebased and merged as commit a148d6fc9ca59a1116cba7b318001a36d21ad622, commit 58df99ea860a8fb6f2b9a47c46ca5e3b9f8dc800, commit 9c24744f45911c1b1d26fe135ae1a88156a316ae,  commit 3fa18c5935cd98e0feb9374ccc77d3a43fe785ce

**Review by trisberg — COMMENTED** [review]
LGTM

**Pull request closed without merging**
