### PR TITLE
Add stream binder for file I/O

### PR DESCRIPTION
**Pull request by dsyer**
Works with target/stream/{input/output} by default, so create those pipes
first to see it working properly (otherwise the app just creates regular
files).

Applied on top of #3

### CODE REVIEW

**Comment by markfisher** [comment]
I'm getting build failures with this: ```Caused by: javax.management.InstanceAlreadyExistsException: org.springframework.integration.monitor:name=integrationMbeanExporter,type=IntegrationMBeanExporter```

**Comment by jldec** [comment]
Depends on stable release of the sc-stream file binder before merging

**Comment by jldec** [comment]
binder has been milestone released
ok to push into this 0.0.2 (even if there is a small startup cost)

**Comment by dsyer** [comment]
Only 1 commit was applied. I would like to re-open so we can look at some of the optimizations I added on top of that. Or I can send another PR?

**Pull request merged**
