### PR TITLE
Support for Publisher in Function signature

### PR DESCRIPTION
**Pull request by dsyer**
User can supply Function<Flux<...>,...> or s/Flux/Publisher/
(or just POJOs).

### CODE REVIEW

**Comment by glyn** [comment]
I like giving function authors the option of _not_ using reactor. The only downside is that the input publisher needs converting to a flux and if 99% of users will be doing this, it's a bit of a pain.

Could we introspect the function and drive it with a signature containing a `Flux` if the function is defined that way? My knowledge of generics is too weak to know...

**Comment by dsyer** [comment]
Take a look at the implementation
of `Flux.from()` (it’s a pass through for an actual `Flux`). I don’t think we could protect it any more efficiently.

**Comment by glyn** [comment]
Efficiency wasn't my concern - it was the amount of boilerplate in the function.

**Comment by dsyer** [comment]
Oh, I see. Well that’s already supported. I didn’t take anything away with this change, just added support for `Publisher`.

**Comment by glyn** [comment]
Nice!

**Comment by trisberg** [comment]
Merged as part of commit 60d675c48817cc75f17af76178afe588a5cd8b42

**Pull request closed without merging**
