### PR TITLE
No need to start Tomcat if the protocol is grpc

### PR DESCRIPTION
**Pull request by dsyer**
The java-invoker.yaml has a hard-coded protocol of "grpc" so it makes
no sense to waste resources listening on port 8080.

### CODE REVIEW

**Review by scothis — COMMENTED** [review]
I agree with the intent here.

Setting ENV in a Dockerfile for a container running under K8s is an anti-pattern. The variable should be set in the k8s resource instead.

It would be nice to approach this more holistically, by the invoker detecting the protocol configured for the function.

**Comment by dsyer** [comment]
I'll take your word for it. You lost me at k8s.

The invoker could certainly handle it though.

**Comment by dsyer** [comment]
Latest change ec7e3fd puts the smarts in the application, waiting for the env var set by the function invoker in the issue above. Can be merged now though (no change in default behaviour).

**Comment by trisberg** [comment]
LGTM

**Pull request merged**
