### PR TITLE
Upgrade Netty to 4.1.39.Final

### PR DESCRIPTION
**Pull request by fbiville**
[This](https://netty.io/news/2019/08/13/4-1-39-Final.html) fixes a number of [HTTP/2 vulnerabilities](https://www.kb.cert.org/vuls/id/605641/).

See https://github.com/projectriff/riff/issues/1354 for more context.

### CODE REVIEW

**Comment by fbiville** [comment]
`reactor-netty` 0.9.0 should be out next week, as confirmed by @simonbasle.
Not sure about `spring-boot-starter-reactor-netty` and `spring-boot-starter-webflux`.

**Comment by simonbasle** [comment]
> `reactor-netty` 0.9.0 should be out next week, as confirmed by @simonbasle.

@fbiville this will be a Release Candidate, `0.9.0.RC1`, though.

**Comment by trisberg** [comment]
Maybe update to latest spring-boot (v2.1.7.RELEASE) and spring-cloud-function (v2.0.2.RELEASE) releases while we are changing the pom.

**Comment by fbiville** [comment]
> Maybe update to latest spring-boot (v2.1.7.RELEASE) and spring-cloud-function (v2.0.2.RELEASE) releases while we are changing the pom.

Done.

There are suspicious stack traces in the [build logs](https://travis-ci.com/projectriff/java-function-invoker/builds/125204874) but the build passes.

**Review by trisberg — APPROVED** [review]
LGTM

We can revisit when Spring Boot 2.1.8.RELEASE and reactor-netty 0.9.0 are out

**Pull request merged**
